build.yml
name: Build Whyred Kernel
on: [push, workflow_dispatch] # workflow_dispatch se aap button daba kar build start kar sakte hain

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3
        with:
          repository: MiCode/Xiaomi_Kernel_OpenSource
          ref: whyred-o-oss
          path: kernel

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential bc libncurses5-dev libssl-dev flex bison git zip gcc-aarch64-linux-gnu

      - name: Build Kernel
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # LKM enable karne ke liye config edit
          sed -i 's/# CONFIG_MODULES is not set/CONFIG_MODULES=y/' arch/arm64/configs/whyred_defconfig
          echo "CONFIG_MODULE_UNLOAD=y" >> arch/arm64/configs/whyred_defconfig
          echo "CONFIG_MODVERSIONS=y" >> arch/arm64/configs/whyred_defconfig
          echo "CONFIG_MODULE_SIG=n" >> arch/arm64/configs/whyred_defconfig
          
          make O=out whyred_defconfig
          make -j$(nproc) O=out
          
      - name: Upload Kernel Image
        uses: actions/upload-artifact@v3
        with:
          name: Kernel-Image
          path: kernel/out/arch/arm64/boot/Image.gz-dtb
 
